#coding=utf-8

import os

WORK_DIRECTORY="."
LOG_DIRECTORY=os.sep.join([WORK_DIRECTORY,"log"])
CONFIG_DIRECTORY=os.sep.join([WORK_DIRECTORY,"conf"])
PROJECTS_DIRECTORY=os.sep.join([WORK_DIRECTORY,"projects"])
TESTLOG_DIRECTORY=os.sep.join([PROJECTS_DIRECTORY,"logs"])
CONFIG_FILE=os.sep.join([CONFIG_DIRECTORY,"autotest.conf"])

CONF_DEFAULT_SECTION="DEFAULT"
CONF_DEFAULT_SECTION_DEFAULT_PROJECT_TYPE="project_types"
CONF_DEFAULT_SECTION_DEFAULT_PROJECT_TYPE_VALUE="NFC安装测试,NFC自动化测试,CENI安装测试,CENI自动化测试,交换机自动化测试"

