# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nfc_project_main.ui'
#
# Created: Mon Apr 24 10:41:21 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_nfcProjectForm(object):
    def setupUi(self, nfcProjectForm):
        nfcProjectForm.setObjectName("nfcProjectForm")
        nfcProjectForm.resize(626, 329)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(nfcProjectForm.sizePolicy().hasHeightForWidth())
        nfcProjectForm.setSizePolicy(sizePolicy)
        self.gridLayout_4 = QtWidgets.QGridLayout(nfcProjectForm)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(nfcProjectForm)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.projectName = QtWidgets.QLineEdit(self.tab)
        self.projectName.setObjectName("projectName")
        self.horizontalLayout_2.addWidget(self.projectName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.projectType = QtWidgets.QLineEdit(self.tab)
        self.projectType.setEnabled(False)
        self.projectType.setObjectName("projectType")
        self.horizontalLayout_3.addWidget(self.projectType)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.keystoneURL = QtWidgets.QLineEdit(self.tab)
        self.keystoneURL.setObjectName("keystoneURL")
        self.horizontalLayout_4.addWidget(self.keystoneURL)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.regionName = QtWidgets.QLineEdit(self.tab)
        self.regionName.setObjectName("regionName")
        self.horizontalLayout_7.addWidget(self.regionName)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.tenant = QtWidgets.QLineEdit(self.tab)
        self.tenant.setObjectName("tenant")
        self.horizontalLayout_5.addWidget(self.tenant)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.password = QtWidgets.QLineEdit(self.tab)
        self.password.setObjectName("password")
        self.horizontalLayout_6.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.publicNetwork = QtWidgets.QLineEdit(self.tab)
        self.publicNetwork.setObjectName("publicNetwork")
        self.horizontalLayout.addWidget(self.publicNetwork)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayoutTest = QtWidgets.QVBoxLayout()
        self.verticalLayoutTest.setObjectName("verticalLayoutTest")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.version = QtWidgets.QLineEdit(self.tab_3)
        self.version.setObjectName("version")
        self.horizontalLayout_9.addWidget(self.version)
        self.verticalLayoutTest.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.currentTest = QtWidgets.QLineEdit(self.tab_3)
        self.currentTest.setObjectName("currentTest")
        self.horizontalLayout_8.addWidget(self.currentTest)
        self.verticalLayoutTest.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_11.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_11.addWidget(self.pushButton_3)
        self.verticalLayoutTest.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10.addLayout(self.verticalLayoutTest)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_10.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_5.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(nfcProjectForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(nfcProjectForm)

    def retranslateUi(self, nfcProjectForm):
        _translate = QtCore.QCoreApplication.translate
        nfcProjectForm.setWindowTitle(_translate("nfcProjectForm", "Form"))
        self.label.setText(_translate("nfcProjectForm", "名称:"))
        self.label_2.setText(_translate("nfcProjectForm", "类型:"))
        self.label_3.setText(_translate("nfcProjectForm", "keystone URL:"))
        self.label_6.setText(_translate("nfcProjectForm", "区域:"))
        self.label_4.setText(_translate("nfcProjectForm", "租户:"))
        self.label_5.setText(_translate("nfcProjectForm", "密码:"))
        self.label_8.setText(_translate("nfcProjectForm", "外部网络:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("nfcProjectForm", "概览"))
        self.label_9.setText(_translate("nfcProjectForm", "测试版本:"))
        self.label_7.setText(_translate("nfcProjectForm", "当前测试:"))
        self.pushButton.setText(_translate("nfcProjectForm", "开始测试"))
        self.pushButton_2.setText(_translate("nfcProjectForm", "暂停测试"))
        self.pushButton_3.setText(_translate("nfcProjectForm", "终止测试"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("nfcProjectForm", "虚拟机名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("nfcProjectForm", "虚拟机UUID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("nfcProjectForm", "浮动IP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("nfcProjectForm", "测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("nfcProjectForm", "控制台"))

